### ISSUE TITLE
Indentation causing broken images and code blocks in some sections

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/see-like-a-bat#3] opened 2016-02-27 03:30 UTC
@MarcScott @LornaLynch @lauraclay

**Comment by LornaLynch** [comment] 2016-02-29 21:06
I think this is fixed now.

**Comment by LornaLynch** [comment] 2016-02-29 21:31
Wait - I have one problem I can't see how to fix: the two code blocks in section 7 of the first worksheet are still formatting with their syntax highlighting showing (i.e. ```python shows in the finished document). It doesn't seem to be happening elsewhere, and I'm not sure what I'm missing. Can anyone else see what the problem is? @lauraclay, @MarcScott?

**Comment by lauraclay** [comment] 2016-03-01 11:51
I've looked at the Markdown, and I can't see what's different with that section- to me, it's indented in the same way as the other code blocks. Will have to investigate this further...

**Comment by LornaLynch** [comment] 2016-03-01 11:53
I know: I can't see what's different about those two blocks. I've checked the instructions for formatting code block on GitHub, and it looks as though everything is as it should be, though evidently not...

**Comment by MarcScott** [comment] 2016-03-02 09:18
Okay, fixed this now I think. Removed the indentation I had there before the triple back ticks.

**Closed as completed by MarcScott** 2016-03-02 09:18 UTC

**Comment by LornaLynch** [comment] 2016-03-02 09:40
Thanks, @MarcScott :)
